all:
	pandoc -o apostila.pdf introducao.md pagebreak.md pensamento_computacional.md pagebreak.md interface_de_programacao.md pagebreak.md problemas_faceis.md pagebreak.md problemas_intermediarios.md pagebreak.md problemas_dificeis.md pagebreak.md conceitos_basicos_de_eletronica.md
	evince apostila.pdf
